title: fes.notice::lang.plugin.name
modelClass: Fes\Notice\Models\Category
list: $/fes/notice/models/category/columns.yaml
recordUrl: fes/notice/categories/update/:id
noRecordsMessage: backend::lang.list.no_records
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
showTree: true